version: '3.8'
services:
  report:
    build: .
    environment:
      TZ: "America/Los_Angeles"
      # Set both of these variables to generate a report for a past date.
      # REPORT_DATE: '2020-08-16'
      # REPORT_CUR_GZ_PATH: 'prefix/report_name/20200801-20200901/assemblyId/report_name-1.csv.gz'
    volumes:
      - './report.html:/root/aws-reporting/report.html'
    depends_on:
      - db
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    expose:
      - '3306'
    volumes:
      - './db/:/docker-entrypoint-initdb.d/:ro'
      - 'aws_reporting_data:/var/lib/mysql'
    environment:
      TZ: "America/Los_Angeles"
      MYSQL_ROOT_PASSWORD: 'hunter2'
      MYSQL_DATABASE: 'aws_reporting'
volumes:
  aws_reporting_data:
