version: '3.8'
services:
  report:
    build: .
    environment:
      TZ: 'America/Los_Angeles'
    volumes:
      - '.:/root/gcp-reporting'
      - '~/.config/gcloud/:/root/.config/gcloud/:ro'
    depends_on:
      - db
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    expose:
      - '3306'
    volumes:
      - './db/:/docker-entrypoint-initdb.d/'
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'hunter2'
      MYSQL_DATABASE: 'gcp_reporting'
      TZ: 'America/Los_Angeles'
