name: Test

on: push

jobs:
  test:
    name: Run linters, doctests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.dev.txt
          pip install -r requirements.txt

      - name: Lint with flake8
        run: make pep8

      - name: Format with PyCharm
        run: |
          # make format
          # This doesn't work yet and I don't know how to fix it.
          make check_clean

      - name: Run doctests
        run: make test
